export const vaccines = [
  {
    id: 0,
    Nom: 'BBIBP-CorV ',
    Inventeurs: 'Sinopharm',
    Lieux_de_production: 'Chine',
    Technologie: 'virus inactivé',
    Quantite: 420,
    Prix_unitaire: 17,
    Approuve: true,
  },
  {
    id: 1,
    Nom: 'Sputnik V ',
    Inventeurs: 'Gamaleya',
    Lieux_de_production: ['Russie', 'Inde'],
    Technologie: 'adenovirus',
    Quantite: 130,
    Prix_unitaire: 12,
    Approuve: false,
  },
  {
    id: 2,
    Nom: 'AZD1222  ',
    Inventeurs: ['AstraZeneca', 'University of Oxford '],
    Lieux_de_production: ['Royaume Unis', 'Brésil', 'Inde'],
    Technologie: 'adenovirus ',
    Quantite: 5028,
    Prix_unitaire: 1.78,
    Approuve: false,
  },
  {
    id: 3,
    Nom: 'Tozinameran ',
    Inventeurs: ['BioNTech', ' Pfizer', 'Fosun Pharma  '],
    Lieux_de_production: ['Allemagne', 'USA'],
    Technologie: 'ARN messager ',
    Quantite: 980,
    Prix_unitaire: 14,
    Approuve: true,

  },
  {
    id: 4,
    Nom: 'mRNA-1273 ',
    Inventeurs: ['Moderna', 'NIAID', 'BARDA'],
    Lieux_de_production: 'USA',
    Technologie: 'ARN messager',
    Quantite: 240,
    Prix_unitaire: 28,
    Approuve: false,
  },
  {
    id: 5,
    Nom: 'Ad26.COV2.S ',
    Inventeurs: ['Johnson & Johnson', 'BIDMC'],
    Lieux_de_production: ['USA', 'Amérique du Sud', 'Ukraine', 'Afrique du Sud'],
    Technologie: 'adenovirus',
    Quantite: 110,
    Prix_unitaire: 31,
    Approuve: false,

  },
];
